version: "3"

services:
    database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: tiempos
    app:
        image: azoriussergh/daw
        depends_on:
            - database
        ports:
            - "8080:8443"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://database/tiempos?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: password